# Generated by Django 3.0.2 on 2020-01-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_stat', models.IntegerField()),
                ('effort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('envolve_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EnvolveFrom', to='pokemon.Pokemon')),
                ('envolve_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EnvolveTo', to='pokemon.Pokemon')),
                ('stats', models.ManyToManyField(to='pokemon.Stat')),
            ],
        ),
    ]
